---
tasks:
  - name: Install yamllint
    init: sudo apt-get install -y yamllint
  - name: Install jarvis
    init: curl https://raw.githubusercontent.com/sebastian-sommerfeld-io/jarvis/main/src/main/install.sh | bash -

vscode:
  extensions:
    - redhat.ansible
    - asciidoctor.asciidoctor-vscode
    - aaron-bond.better-comments
    - ms-azuretools.vscode-docker
    - hashicorp.terraform
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-python.python
    - rebornix.ruby
    - timonwong.shellcheck
    - wingrunr21.vscode-ruby
    - ms-python.python
    - redhat.vscode-yaml
    - jebbs.plantuml
    - vscjava.vscode-java-pack
    - pomdtr.markdown-kroki
    - recode4dev.jenkinsfile
    - cschleiden.vscode-github-actions
